# GitHub workflow for PR validation
name: PR Validation

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

# Add top-level permissions to ensure access across all jobs
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  validate:
    name: Validate Build & Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm i --no-fund --no-audit

      - name: Type check
        run: npm run typecheck
        continue-on-error: false

      - name: Lint check
        run: npm run lint
        continue-on-error: false

      - name: Prettier format check
        run: npm run prettier:check
        continue-on-error: false

      - name: Run tests
        run: npm run test:coverage
        continue-on-error: false

      - name: Build application
        run: npm run build
        continue-on-error: false

      # Security audit (informational only)
      - name: Security audit
        run: npm audit --audit-level=high
        continue-on-error: true

  # Additional job for dependency analysis
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC
